banking_dbt:
  target: dev

  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '15432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'banking_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'banking_oltp') }}"
      schema: dbt_dev
      threads: 4
